export const zh = {
  site: { home: "帕鲁世界攻略", calculator: "配种计算器", pals: "帕鲁图鉴", english: "English", chinese: "中文", search: "搜索", menu: "菜单" },
  breeding: {
    modes: { parents: "双亲 → 子代", target: "目标帕鲁 → 父母组合", offspring: "单个帕鲁 → 可配出的子代", availableRoute: "已有帕鲁 → 目标帕鲁", shortest: "最短配种路线", available: "我现在能配出什么" },
    descriptions: { parents: "选择两个帕鲁，查看它们能配出的子代。", target: "选择目标帕鲁，查看所有直接父母组合。", offspring: "查看选定帕鲁可以配出的全部结果。", availableRoute: "选择你已有的帕鲁，寻找通往目标帕鲁的路线。", shortest: "寻找最少配种步骤的目标路线。", available: "查看你已有的帕鲁现在可以配出什么。" },
    choose: "选择帕鲁", chooseBoth: "选择两个父母后计算", search: "搜索中英文名称或帕鲁编号", change: "更换帕鲁", choosePal: "选择帕鲁", no: "编号", offspring: "子代", result: "配种结果", waiting: "等待父母", results: "结果", outcomes: "个结果", noResult: "没有找到配种结果。", clear: "清除", swap: "交换", copyCombination: "复制组合", viewDetails: "查看帕鲁详情", viewDatabase: "在图鉴中查看", databasePals: "个帕鲁", parentCombinations: "父母组合", found: "找到", showing: "显示", combinations: "个组合", allShown: "已显示全部组合", filterParent: "按父母筛选", allParents: "全部父母", allPals: "全部帕鲁", select: "选择", available: "可用", selected: "已选择", loadMore: "加载更多", loading: "加载中…", maximumGenerations: "最大代数", start: "起始帕鲁", target: "目标帕鲁", advanced: "高级选项", exclude: "排除帕鲁", selectPals: "选择帕鲁", clearAll: "全部清除", routeResults: "路线结果", upTo: "最多", generations: "代", chooseRouteInputs: "选择起始帕鲁和目标帕鲁来计算路线。", noRoute: "在当前代数限制内没有找到路线。", finding: "正在寻找配种路线…", findRoutes: "查找配种路线", savedRoster: "你保存的配种名单", addOwned: "选择我已经拥有的帕鲁", owned: "已有帕鲁", selectOwned: "选择你已有的帕鲁", edit: "编辑", breedNow: "现在配种", addToSee: "添加已有帕鲁，查看现在可以配出的子代。", chooseParent: "选择一个父母，查看全部子代。", selectTarget: "选择目标帕鲁", error: "配种数据暂时不可用。", retry: "重试", gender: "性别限定结果", requiresTwo: "需要两个兼容的个体", usePair: "使用这组父母", close: "关闭", showingOf: "显示", pals: "个帕鲁", selectedPals: "个已选帕鲁", targetAlready: "目标帕鲁已经在已有名单中 · 0 代", step: "步骤", copyRoute: "复制路线", copyLink: "复制链接", runSearch: "执行搜索后查看路线", inputsChanged: "输入已变化，请重新查找路线。" },
  pals: { database: "帕鲁图鉴", all: "全部帕鲁", current: "当前帕鲁", browse: "按名称、帕鲁编号、属性、工作适应性和配种数据浏览全部帕鲁。", search: "搜索中英文名称或帕鲁编号", ariaSearch: "搜索帕鲁图鉴", new: "1.0 新增", newOnly: "仅显示新增", element: "按属性筛选", work: "按工作筛选", any: "任意", allMatch: "全部匹配", available: "个帕鲁", match: "个帕鲁符合筛选", found: "找到", pal: "帕鲁", pals: "个帕鲁", sort: "排序", clear: "清除全部", selected: "个已选帕鲁", clearSelection: "清除选择", showing: "显示", of: "，共", previous: "上一页", next: "下一页", cancel: "取消", apply: "应用", minimum: "最低等级", level: "等级", noResults: "没有找到帕鲁", tryAgain: "请尝试其他搜索词，或清除一个筛选条件。", breeding: "配种", findParents: "查找父母", partnerSkill: "伙伴技能", number: "编号", rarity: "稀有度", hp: "生命值", power: "配种力", defense: "防御", price: "价格", stamina: "耐力", riding: "骑乘速度", run: "奔跑速度", page: "第", currentSnapshot: "当前数据快照", howTo: "如何使用帕鲁图鉴" }
} as const;

export type Locale = "en" | "zh";
