"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import PalMark from "../components/pal-mark";
import { PalData, WorkKey, workGlyphs, workLabels, pals } from "../lib/game-data";
import { filterPals, highestWorkLevel, MatchMode, PaldexFilters, PaldexSort, parsePaldexFilters, serializePaldexFilters, sortPals } from "../lib/paldex";

const workTypes = Object.keys(workLabels) as WorkKey[];
const elementOptions = ["Neutral", "Fire", "Water", "Grass", "Electric", "Ice", "Ground", "Dark", "Dragon"];
type Sheet = "elements" | "work" | null;
const dash = (value: string | number | null) => value ?? "—";

function WorkBadges({ pal }: { pal: PalData }) {
  const entries = Object.entries(pal.work) as [WorkKey, number][];
  return entries.length ? <p className="mini-work">{entries.map(([key, level]) => <span key={key} title={workLabels[key]}>{workGlyphs[key]} {level}</span>)}</p> : <span className="muted-dash">—</span>;
}

export default function PaldexClient({ initialPage: _initialPage = 1 }: { initialPage?: number }) {
  void _initialPage;
  const router = useRouter();
  const searchParams = useSearchParams();
  const filters = useMemo(() => parsePaldexFilters(new URLSearchParams(searchParams.toString())), [searchParams]);
  const [sheet, setSheet] = useState<Sheet>(null);
  const [draftElements, setDraftElements] = useState<string[]>([]);
  const [draftElementMode, setDraftElementMode] = useState<MatchMode>("any");
  const [draftWork, setDraftWork] = useState<WorkKey[]>([]);
  const [draftWorkMode, setDraftWorkMode] = useState<MatchMode>("any");
  const [draftWorkLevel, setDraftWorkLevel] = useState(0);
  const visible = useMemo(() => sortPals(filterPals(pals, filters), filters.sort), [filters]);
  const update = (patch: Partial<PaldexFilters>) => { const query = serializePaldexFilters({ ...filters, ...patch }).toString(); router.push(query ? `/paldex?${query}` : "/paldex", { scroll: false }); };
  const toggle = <T extends string,>(items: T[], item: T) => items.includes(item) ? items.filter((value) => value !== item) : [...items, item];
  const openSheet = (next: Exclude<Sheet, null>) => { if (next === "elements") { setDraftElements(filters.elements); setDraftElementMode(filters.elementMode); } else { setDraftWork(filters.work); setDraftWorkMode(filters.workMode); setDraftWorkLevel(filters.workLevel); } setSheet(next); };
  const applySheet = () => { if (sheet === "elements") update({ elements: draftElements, elementMode: draftElementMode }); if (sheet === "work") update({ work: draftWork, workMode: draftWorkMode, workLevel: draftWorkLevel }); setSheet(null); };
  const clearAll = () => update({ q: "", elements: [], elementMode: "any", work: [], workMode: "any", workLevel: 0, types: ["pal"], sort: "number" });
  const hasFilters = Boolean(filters.q || filters.elements.length || filters.work.length || filters.workLevel || filters.types.join(",") !== "pal" || filters.sort !== "number");
  const highest = (pal: PalData) => highestWorkLevel(pal);

  return <section className="database-workspace paldex-workspace paldex-wide" aria-label="Palworld Paldeck filters and results">
    <div className="paldex-control-bar">
      <label className="paldex-search"><span>⌕</span><input value={filters.q} onChange={(event) => update({ q: event.target.value })} placeholder="Search English name or Paldeck number…" aria-label="Search Paldeck" /></label>
      <button type="button" className="paldex-filter-open" onClick={() => openSheet("elements")}><span>Element</span><strong>{filters.elements.length ? `${filters.elements.length} selected` : "Any element"}</strong></button>
      <button type="button" className="paldex-filter-open" onClick={() => openSheet("work")}><span>Work suitability</span><strong>{filters.work.length ? `${filters.work.length} selected` : "Any work"}</strong></button>
      <div className="paldex-tabs" aria-label="Paldex view"><button type="button" className={filters.view === "overview" ? "active" : ""} onClick={() => update({ view: "overview" })}>Overview</button><button type="button" className={filters.view === "work" ? "active" : ""} onClick={() => update({ view: "work" })}>Work</button><button type="button" className={filters.view === "stats" ? "active" : ""} onClick={() => update({ view: "stats" })}>Stats</button></div>
    </div>
    <div className="paldex-toolbar"><p><strong>{visible.length}</strong> {visible.length === 1 ? "entry" : "entries"} found</p><div><label><span>Sort</span><select aria-label="Sort Paldeck" value={filters.sort} onChange={(event) => update({ sort: event.target.value as PaldexSort })}><option value="number">Paldeck number</option><option value="name">Name A–Z</option><option value="hp">HP</option><option value="ranged">Ranged attack</option><option value="defense">Defense</option><option value="stamina">Stamina</option><option value="rarity">Rarity</option><option value="food">Food consumption</option><option value="speed">Run speed</option><option value="work">Highest work level</option><option value="power-low">Breeding power: low first</option><option value="power-high">Breeding power: high first</option></select></label>{hasFilters && <button type="button" className="paldex-reset" onClick={clearAll}>Clear all</button>}</div></div>
    {hasFilters && <div className="paldex-chips" aria-label="Selected filters">{filters.elements.map((value) => <button key={value} onClick={() => update({ elements: toggle(filters.elements, value) })}>{value} ×</button>)}{filters.work.map((value) => <button key={value} onClick={() => update({ work: toggle(filters.work, value) })}>{workLabels[value]} ×</button>)}{filters.elements.length > 1 && <span>Elements: {filters.elementMode}</span>}{filters.work.length > 1 && <span>Work: {filters.workMode}</span>}{filters.workLevel > 0 && <span>Work level {filters.workLevel}+</span>}</div>}
    {visible.length ? <><div className="paldex-table-wrap"><table className={`paldex-table ${filters.view}-view`}><thead><tr>{filters.view === "overview" ? <><th>Pal</th><th>No.</th><th>Element</th><th>Work Suitability</th><th>Rarity</th><th>HP</th><th>Defense</th><th>Breeding Power</th></> : filters.view === "work" ? <><th>Pal</th><th>Element</th><th>Work Suitability</th><th>Highest Work Level</th><th>Food</th><th>Nocturnal</th></> : <><th>Pal</th><th>Rarity</th><th>HP</th><th>Ranged Attack</th><th>Defense</th><th>Stamina</th><th>Run Speed</th></>}</tr></thead><tbody>{visible.map((pal) => <tr key={pal.id}><td><Link href={`/pals/${pal.slug}`}><PalMark pal={pal} /><span><strong>{pal.name}</strong><small>{pal.kind === "pal" ? "Pal" : "Crossover creature"}</small></span></Link></td>{filters.view === "overview" ? <><td>{pal.number}</td><td>{pal.elements.join(" / ") || "—"}</td><td><WorkBadges pal={pal} /></td><td>{dash(pal.rarity)}</td><td>{dash(pal.stats.hp)}</td><td>{dash(pal.stats.defense)}</td><td>{pal.power}</td></> : filters.view === "work" ? <><td>{pal.elements.join(" / ") || "—"}</td><td><WorkBadges pal={pal} /></td><td>{highest(pal) || "—"}</td><td>{dash(pal.foodConsumption)}</td><td>{pal.nocturnal === null ? "—" : pal.nocturnal ? "Yes" : "No"}</td></> : <><td>{dash(pal.rarity)}</td><td>{dash(pal.stats.hp)}</td><td>{dash(pal.stats.rangedAttack)}</td><td>{dash(pal.stats.defense)}</td><td>{dash(pal.stats.stamina)}</td><td>{dash(pal.movement.run)}</td></>}</tr>)}</tbody></table></div><div className="paldex-mobile-cards">{visible.map((pal) => <Link href={`/pals/${pal.slug}`} key={pal.id}><PalMark pal={pal} /><div><small>No. {pal.number}{pal.elements.length ? ` · ${pal.elements.join(" / ")}` : ""}</small><h2>{pal.name}</h2><WorkBadges pal={pal} />{filters.view === "overview" ? <p>HP {dash(pal.stats.hp)} · DEF {dash(pal.stats.defense)} · Rarity {dash(pal.rarity)}</p> : filters.view === "work" ? <p>Top work {highest(pal) || "—"} · Food {dash(pal.foodConsumption)}</p> : <p>Ranged {dash(pal.stats.rangedAttack)} · Stamina {dash(pal.stats.stamina)} · Run {dash(pal.movement.run)}</p>}</div></Link>)}</div></> : <div className="paldex-empty"><span>⌕</span><h2>No Pals found</h2><p>Try another search or clear one of the filters.</p><button type="button" onClick={clearAll}>Clear all</button></div>}
    {sheet && <div className="paldex-filter-backdrop" role="presentation" onClick={() => setSheet(null)}><section className="paldex-filter-sheet" role="dialog" aria-modal="true" aria-label={sheet === "elements" ? "Element filters" : "Work suitability filters"} onClick={(event) => event.stopPropagation()}><header><h2>{sheet === "elements" ? "Element" : "Work Suitability"}</h2><button type="button" onClick={() => setSheet(null)}>Cancel</button></header>{sheet === "elements" ? <><div className="paldex-filter-options">{elementOptions.map((item) => <button type="button" key={item} className={draftElements.includes(item) ? "active" : ""} onClick={() => setDraftElements(toggle(draftElements, item))}>{item}</button>)}</div>{draftElements.length > 1 && <div className="paldex-match-mode"><button type="button" className={draftElementMode === "any" ? "active" : ""} onClick={() => setDraftElementMode("any")}>Match any</button><button type="button" className={draftElementMode === "all" ? "active" : ""} onClick={() => setDraftElementMode("all")}>Match all</button></div>}</> : <><div className="paldex-filter-options work-options">{workTypes.map((item) => <button type="button" key={item} className={draftWork.includes(item) ? "active" : ""} onClick={() => setDraftWork(toggle(draftWork, item))}>{workGlyphs[item]} {workLabels[item]}</button>)}</div><label className="paldex-min-level">Minimum level<select value={draftWorkLevel} onChange={(event) => setDraftWorkLevel(Number(event.target.value))}><option value="0">Any</option>{[2, 3, 4, 5, 6, 7, 8].map((level) => <option key={level} value={level}>{level}+</option>)}</select></label>{draftWork.length > 1 && <div className="paldex-match-mode"><button type="button" className={draftWorkMode === "any" ? "active" : ""} onClick={() => setDraftWorkMode("any")}>Match any</button><button type="button" className={draftWorkMode === "all" ? "active" : ""} onClick={() => setDraftWorkMode("all")}>Match all</button></div>}</>}<footer><button type="button" className="paldex-sheet-clear" onClick={() => { if (sheet === "elements") { setDraftElements([]); setDraftElementMode("any"); } else { setDraftWork([]); setDraftWorkMode("any"); setDraftWorkLevel(0); } }}>Clear</button><button type="button" className="paldex-sheet-apply" onClick={applySheet}>Apply</button></footer></section></div>}
  </section>;
}
