import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../components/site-header";
import MapClient from "./map-client";
import { absoluteUrl, createBreadcrumbSchema } from "../lib/seo";
import { mapDataUrl, mapCoordinateNote, type MapCategory } from "../../data/map";
import mapData from "../../public/data/map-locations.json";

const title = "Palworld Map 1.0 – Interactive Map, Locations & Resources";
const description = "Explore the Palworld Map 1.0 to find Alpha Pals, fast travel points, dungeons, resources, treasure chests, Pal eggs, merchants, towers, settlements, and other important locations.";

export const metadata: Metadata = { title, description, robots: { index: true, follow: true }, alternates: { canonical: absoluteUrl("/map") }, openGraph: { title, description, url: absoluteUrl("/map"), siteName: "Palworld Guide", type: "website", images: [{ url: absoluteUrl("/map/Palworld_Map_Complete.png"), width: 4096, height: 4096, alt: "Complete Palworld Map 1.0" }] } };

const breadcrumbSchema = createBreadcrumbSchema([{ name: "Home", path: "/" }, { name: "Map", path: "/map" }]);
const pageSchema = { "@context": "https://schema.org", "@type": "WebPage", name: title, headline: "Palworld Map 1.0", description, url: absoluteUrl("/map"), isAccessibleForFree: true, inLanguage: "en" };
const categories = (mapData.categories as MapCategory[]).map((category) => ({ name: category.name, icon: category.icon }));

export default function MapPage() {
  return <main id="main-content" className="map-page min-h-screen bg-canvas text-foreground"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(pageSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} /><SiteHeader current="/map" /><div className="map-page-wrap"><nav className="map-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">›</span><span>Map</span></nav><header className="map-page-header"><div><p className="map-kicker">Palworld 1.0 · Field atlas</p><h1>Palworld Map 1.0</h1><p>Explore the latest Palworld interactive map for version 1.0. Search and filter Alpha Pals, fast travel points, dungeons, resources, treasure chests, Pal eggs, merchants, towers, settlements, and other important locations across the full Palworld map.</p></div><div className="map-header-stat"><strong>{new Intl.NumberFormat("en-US").format(mapData.locations.length)}</strong><span>locations indexed</span><small>Palpagos map · 1.0 data</small></div></header><MapClient initialCategories={categories} locationCount={mapData.locations.length} /><section className="map-seo-content"><h2>Palworld Interactive Map</h2><p>This Palworld Map 1.0 brings the full Palpagos map into one searchable field guide. Use the interactive view to explore the supplied map image and location dataset without leaving the page.</p><h2>Palworld Map Locations</h2><p>The map indexes {new Intl.NumberFormat("en-US").format(mapData.locations.length)} location records, including Pal encounters, Alpha Pals, resource nodes, chests, eggs, travel points, dungeons, merchants, towers, and other map markers.</p><h2>Palworld Map Categories</h2><p>Use the layer panel to switch categories on or off. Counts are calculated from the current location data, so you can quickly see which filters are active and how many markers remain visible.</p><h2>How to Use the Palworld Map</h2><p>Search by name or description, select a category, then drag the map to pan and use the scroll wheel, zoom controls, or touch gestures to zoom. Click a marker to open its location card, coordinates, and share action. Use Show all or Clear filters to reset the layer state.</p><h2>What Is New in the Palworld 1.0 Map?</h2><p>The current map data is the prepared Palworld 1.0 map snapshot used by this project. {mapCoordinateNote} The map is kept as a local asset with an R2-compatible URL fallback through the project asset pipeline.</p><p className="map-data-note">Map data endpoint: <code>{mapDataUrl}</code></p></section></div><footer className="map-footer">Independent fan-made resource · Palworld is a trademark of its respective owner.</footer></main>;
}
