"use client";

import Link from "next/link";
import Image from "next/image";
import { useEffect, useMemo, useRef, useState } from "react";
import PalMark from "../components/pal-mark";
import { ElementIcon, WorkSuitabilityIcon } from "../components/pal-icons";
import { BreedingData, PalData, pals, WorkKey, workLabels } from "../lib/game-data";
import { assetUrl } from "../lib/assets";
import { findPalDropsLocations } from "../lib/pal-drops-locations";
import { availableOffspring, comparePals, findOffspring, findParentPairs, findRoutes, pairResults, type BreedingResult } from "./breeding/core";
import { readAvailablePals, saveAvailablePals } from "./breeding/storage";
import { zh, type Locale } from "../i18n/zh";
import { getPalNameZh } from "../lib/pal-names-zh";

type Mode = "parents" | "target" | "offspring" | "available-route" | "shortest" | "available";
type Slot = "a" | "b" | "target" | "parent" | "start" | "parent-filter" | "offspring-filter" | "exclude" | "available" | null;
const modes: [Mode, string][] = [["parents", "Parents → Child"], ["target", "Target → Parents"], ["offspring", "One Parent → Offspring"], ["available-route", "Owned Pals → Target"], ["shortest", "Shortest Route"], ["available", "What Can I Breed Now"]];
const modeDescriptions: Record<Mode, string> = { parents: "Pick two Pals to see their offspring.", target: "Choose a Pal to reveal every direct parent pair.", offspring: "See every result a selected parent can create.", "available-route": "Select the Pals you own and find a breeding route to your target.", shortest: "Find the fewest breeding steps to your target.", available: "See what your Available Pals can breed now." };
const PICKER_BATCH_SIZE = 60;
const defaultPickerSlots: Record<Mode, Exclude<Slot, null>> = { parents: "a", target: "target", offspring: "parent", "available-route": "available", shortest: "start", available: "available" };

function palLabel(pal: PalData, locale: Locale) {
  return locale === "zh" ? getPalNameZh(pal.name) ?? pal.name : pal.name;
}

function LocalizedPalName({ pal, locale = "en" }: { pal: PalData; locale?: Locale }) {
  const chineseName = locale === "zh" ? getPalNameZh(pal.name) : undefined;
  return chineseName ? <span className="localized-pal-name"><span>{chineseName}</span><small>{pal.name}</small></span> : <>{pal.name}</>;
}

function PickerPalMeta({ pal, locale }: { pal: PalData; locale: Locale }) {
  const details = findPalDropsLocations(pal.slug);
  const drops = details?.drops.filter((drop) => drop.icon).slice(0, 3) ?? [];
  const workEntries = (Object.entries(pal.work) as [WorkKey, number][]).sort(([, first], [, second]) => second - first).slice(0, 3);
  const dropLabel = locale === "zh" ? "掉落物" : "Drops";
  const workLabel = locale === "zh" ? "工作适应性" : "Work suitability";
  return <span className="pal-picker-card-meta">
    <span className="pal-picker-elements" aria-label={locale === "zh" ? "属性" : "Elements"}>{pal.elements.map((element) => <ElementIcon key={element} element={element} />)}</span>
    {drops.length > 0 && <span className="pal-picker-drops" aria-label={dropLabel}>
      {drops.map((drop) => <Image key={`${drop.name}-${drop.icon}`} src={assetUrl(`/icons/palworld/drops/${drop.icon}`)} alt="" title={`${drop.name}${drop.quantity ? ` · ${drop.quantity}` : ""}${drop.chance ? ` · ${drop.chance}` : ""}`} width={18} height={18} unoptimized />)}
      {details && details.drops.length > drops.length && <em>+{details.drops.length - drops.length}</em>}
    </span>}
    {workEntries.length > 0 && <span className="pal-picker-work" aria-label={workLabel}>
      {workEntries.map(([key, level]) => <span className="pal-picker-work-item" key={key} title={`${workLabels[key]} · Level ${level}`}><WorkSuitabilityIcon work={key} /><b>{level}</b></span>)}
      {Object.keys(pal.work).length > workEntries.length && <em>+{Object.keys(pal.work).length - workEntries.length}</em>}
    </span>}
  </span>;
}

function PickerFilterSelect({ value, options, allLabel, ariaLabel, onChange, formatOption }: { value: string; options: string[]; allLabel: string; ariaLabel: string; onChange: (value: string) => void; formatOption?: (value: string) => string }) {
  const [open, setOpen] = useState(false);
  const controlRef = useRef<HTMLDivElement>(null);
  const selectedLabel = value ? formatOption?.(value) ?? value : allLabel;
  useEffect(() => {
    if (!open) return;
    const close = (event: MouseEvent) => { if (!controlRef.current?.contains(event.target as Node)) setOpen(false); };
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); };
    document.addEventListener("mousedown", close);
    document.addEventListener("keydown", escape);
    return () => { document.removeEventListener("mousedown", close); document.removeEventListener("keydown", escape); };
  }, [open]);
  return <div ref={controlRef} className="picker-filter-select"><button type="button" className="picker-filter-trigger" aria-haspopup="listbox" aria-expanded={open} aria-label={ariaLabel} onClick={() => setOpen((current) => !current)}><span>{selectedLabel}</span><b aria-hidden="true">⌄</b></button>{open && <div className="picker-filter-menu" role="listbox" aria-label={ariaLabel}><button type="button" role="option" aria-selected={!value} className={!value ? "selected" : ""} onClick={() => { onChange(""); setOpen(false); }}>{!value && <span aria-hidden="true">✓</span>}{allLabel}</button>{options.map((option) => <button type="button" role="option" aria-selected={value === option} className={value === option ? "selected" : ""} key={option} onClick={() => { onChange(option); setOpen(false); }}>{value === option && <span aria-hidden="true">✓</span>}{formatOption?.(option) ?? option}</button>)}</div>}</div>;
}

function PalPickerPanel({ embedded, locale, slot, available, search, visibleSearch, pickerLoading, query, element, rarity, elements, rarities, searchInputRef, setQuery, onElementChange, onRarityChange, onChoose, onClearAvailable, onClose, onLoadMore }: { embedded: boolean; locale: Locale; slot: Exclude<Slot, null>; available: string[]; search: PalData[]; visibleSearch: PalData[]; pickerLoading: boolean; query: string; element: string; rarity: string; elements: string[]; rarities: number[]; searchInputRef: React.RefObject<HTMLInputElement | null>; setQuery: (value: string) => void; onElementChange: (value: string) => void; onRarityChange: (value: string) => void; onChoose: (pal: PalData) => void; onClearAvailable: () => void; onClose: () => void; onLoadMore: () => void }) {
  const t = locale === "zh" ? zh.breeding : undefined;
  const title = embedded ? ({ a: "Choosing Parent A", b: "Choosing Parent B", target: "Choosing Target Pal", parent: "Choosing Parent Pal", start: "Choosing Starting Pal", "parent-filter": "Choosing Parent Filter", "offspring-filter": "Choosing Offspring Filter", exclude: "Choosing Pals to Exclude", available: "Choosing Available Pals" } satisfies Record<Exclude<Slot, null>, string>)[slot] : (t?.choose ?? "Choose a Pal");
  const items = embedded ? search : visibleSearch;
  return <section className={embedded ? "home-pal-picker home-inline-pal-picker" : "pal-picker home-pal-picker"} role={embedded ? undefined : "dialog"} aria-modal={embedded ? undefined : true} aria-labelledby="pal-selector-title" onClick={(event) => event.stopPropagation()} onKeyDown={(event) => { if (event.key === "Escape") { event.preventDefault(); onClose(); } }}>
    <header><div><h2 id="pal-selector-title">{title}</h2><p>{embedded ? `${search.length} ${t?.pals ?? "Pals"}` : null}</p></div><div>{slot === "available" && available.length > 0 && <button type="button" className="pal-picker-clear" onClick={onClearAvailable}>Clear selected</button>}{!embedded && <button type="button" aria-label={t?.close ?? "Close Pal selector"} onClick={onClose}>×</button>}</div></header>
    <div className="home-picker-toolbar"><input ref={searchInputRef} value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && items[0]) onChoose(items[0]); }} placeholder={t?.search ?? "Search name or Paldeck number…"} aria-label={t?.search ?? "Search Pals by name or Paldeck number"} /><PickerFilterSelect value={element} options={elements} allLabel={locale === "zh" ? "全部属性" : "All elements"} ariaLabel={locale === "zh" ? "按属性筛选" : "Filter by element"} onChange={onElementChange} /><PickerFilterSelect value={rarity} options={rarities.map(String)} allLabel={locale === "zh" ? "全部稀有度" : "All rarities"} ariaLabel={locale === "zh" ? "按稀有度筛选" : "Filter by rarity"} onChange={onRarityChange} formatOption={(value) => locale === "zh" ? `稀有度 ${value}` : `Rarity ${value}`} /></div>
    <p className="pal-picker-progress">{t?.showing ?? "Showing"} {items.length} / {search.length} {t?.pals ?? "Pals"}</p>
    <div className="pal-picker-grid">{items.map((pal) => <button type="button" key={pal.id} className={slot === "available" && available.includes(pal.id) ? "selected" : ""} aria-pressed={slot === "available" ? available.includes(pal.id) : undefined} onClick={() => onChoose(pal)}><PalMark pal={pal} small /><span className="pal-picker-card-copy"><b><LocalizedPalName pal={pal} locale={locale} /></b><small>{t?.no ?? "No."} {pal.number}</small><PickerPalMeta pal={pal} locale={locale} /></span></button>)}</div>
    {!embedded && visibleSearch.length < search.length && <button type="button" className="pal-picker-load-more" disabled={pickerLoading} aria-busy={pickerLoading} onClick={onLoadMore}>{pickerLoading ? (t?.loading ?? "Loading…") : (t?.loadMore ?? "Load more")}</button>}
  </section>;
}

function Result({ result, usePair, showDatabaseLink = false, locale = "en" }: { result: BreedingResult; usePair?: () => void; showDatabaseLink?: boolean; locale?: Locale }) {
  const t = locale === "zh" ? zh.breeding : undefined;
  const palHref = (slug: string) => locale === "zh" ? `/zh/pals?ids=${encodeURIComponent(slug)}` : `/pals/${slug}`;
  return <article className="breed-row"><span><PalMark pal={result.first} small />{result.genders?.[0] && <em>{result.genders[0]}</em>}<Link href={palHref(result.first.slug)}><LocalizedPalName pal={result.first} locale={locale} /></Link></span><b>+</b><span><PalMark pal={result.second} small />{result.genders?.[1] && <em>{result.genders[1]}</em>}<Link href={palHref(result.second.slug)}><LocalizedPalName pal={result.second} locale={locale} /></Link></span><b>→</b><span><PalMark pal={result.child} small /><Link href={palHref(result.child.slug)}><LocalizedPalName pal={result.child} locale={locale} /></Link></span>{result.genders && <small>{t?.gender ?? "Gender-specific result"}</small>}{result.requiresTwo && <small>{t?.requiresTwo ?? "Requires two compatible individuals"}</small>}{showDatabaseLink && <DatabaseResultLink pals={[result.first, result.second, result.child]} locale={locale} />}{usePair && <button onClick={usePair}>{t?.usePair ?? "Use pair"}</button>}</article>;
}

function DatabaseResultLink({ pals: resultPals, locale = "en" }: { pals: PalData[]; locale?: Locale }) {
  const slugs = Array.from(new Set(resultPals.map((pal) => pal.slug).filter((slug) => pals.some((pal) => pal.slug === slug))));
  if (!slugs.length) return null;
  const href = locale === "zh" ? `/zh/pals?ids=${slugs.join(",")}` : slugs.length === 1 ? `/pals/${slugs[0]}` : `/pals?ids=${slugs.join(",")}`;
  return <Link className="breed-database-link" href={href}>{slugs.length === 1 ? (locale === "zh" ? zh.breeding.viewDetails : "View Pal Details") : `${slugs.length} ${locale === "zh" ? zh.breeding.databasePals : "Pals in Database"}`}</Link>;
}

function GenerationSelect({ value, onChange, locale = "en" }: { value: number; onChange: (value: number) => void; locale?: Locale }) {
  const [open, setOpen] = useState(false);
  const controlRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    const close = (event: MouseEvent) => { if (!controlRef.current?.contains(event.target as Node)) setOpen(false); };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, [open]);
  return <div ref={controlRef} className="home-number-control"><span>{locale === "zh" ? zh.breeding.maximumGenerations : "Maximum generations"}</span><button type="button" className="home-generation-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((current) => !current)}><strong>{value}</strong><b aria-hidden="true">⌄</b></button>{open && <div className="home-generation-menu" role="listbox" aria-label={locale === "zh" ? zh.breeding.maximumGenerations : "Maximum generations"}>{[1, 2, 3, 4, 5].map((generation) => <button type="button" role="option" aria-selected={generation === value} className={generation === value ? "selected" : ""} key={generation} onClick={() => { onChange(generation); setOpen(false); }}>{generation}</button>)}</div>}</div>;
}

export default function BreedingClient({ embedded = false, locale = "en" }: { embedded?: boolean; locale?: Locale }) {
  const t = locale === "zh" ? zh.breeding : undefined;
  const modeLabels: Record<Mode, string> = locale === "zh" ? { parents: zh.breeding.modes.parents, target: zh.breeding.modes.target, offspring: zh.breeding.modes.offspring, "available-route": zh.breeding.modes.availableRoute, shortest: zh.breeding.modes.shortest, available: zh.breeding.modes.available } : Object.fromEntries(modes) as Record<Mode, string>;
  const modeCopy: Record<Mode, string> = locale === "zh" ? { parents: zh.breeding.descriptions.parents, target: zh.breeding.descriptions.target, offspring: zh.breeding.descriptions.offspring, "available-route": zh.breeding.descriptions.availableRoute, shortest: zh.breeding.descriptions.shortest, available: zh.breeding.descriptions.available } : modeDescriptions;
  const [matrix, setMatrix] = useState<BreedingData>({});
  const [error, setError] = useState(false);
  const [mode, setMode] = useState<Mode>("parents");
  const [a, setA] = useState<PalData | undefined>();
  const [b, setB] = useState<PalData | undefined>();
  const [target, setTarget] = useState<PalData | undefined>();
  const [parent, setParent] = useState<PalData | undefined>();
  const [start, setStart] = useState<PalData | undefined>();
  const [slot, setSlot] = useState<Slot>(embedded ? defaultPickerSlots.parents : null);
  const [query, setQuery] = useState("");
  const [pickerElement, setPickerElement] = useState("");
  const [pickerRarity, setPickerRarity] = useState("");
  const [pickerLimit, setPickerLimit] = useState(PICKER_BATCH_SIZE);
  const [pickerLoading, setPickerLoading] = useState(false);
  const [available, setAvailable] = useState<string[]>([]);
  const [max, setMax] = useState(3);
  const [excluded, setExcluded] = useState<string[]>([]);
  const [parentFilter, setParentFilter] = useState<string | undefined>();
  const [offspringFilter, setOffspringFilter] = useState<string | undefined>();
  const [page, setPage] = useState(1);
  const [targetVisibleCount, setTargetVisibleCount] = useState(50);
  const [targetSelectionVersion, setTargetSelectionVersion] = useState(0);
  const [availableRouteQuery, setAvailableRouteQuery] = useState<{ available: string[]; targetId: string; max: number } | null>(null);
  const [availableRouteLoading, setAvailableRouteLoading] = useState(false);
  const [availableRouteVersion, setAvailableRouteVersion] = useState(0);
  const [urlRestored, setUrlRestored] = useState(false);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const pickerTriggerRef = useRef<HTMLElement | null>(null);
  const targetResultsRef = useRef<HTMLElement>(null);
  const lastScrolledTargetRef = useRef<string | undefined>(undefined);
  const byId = useMemo(() => new Map(pals.map((pal) => [pal.id, pal])), []);

  useEffect(() => { fetch(assetUrl("/data/breeding.json")).then((r) => r.ok ? r.json() : Promise.reject()).then(setMatrix).catch(() => setError(true)); }, []);
  useEffect(() => { const frame = requestAnimationFrame(() => { const params = new URLSearchParams(window.location.search); const requestedMode = params.get("mode"); const restoredMode = modes.some(([id]) => id === requestedMode) ? requestedMode as Mode : "parents"; const palFromParam = (name: string) => pals.find((pal) => pal.id === params.get(name)); setMode(restoredMode); if (embedded) setSlot(defaultPickerSlots[restoredMode]); setA(palFromParam("parentA")); setB(palFromParam("parentB")); setTarget(palFromParam("target")); setParent(palFromParam("parent")); setStart(palFromParam("starting")); setMax(Math.min(5, Math.max(1, Number(params.get("max")) || 3))); setAvailable(readAvailablePals()); setUrlRestored(true); }); return () => cancelAnimationFrame(frame); }, [embedded]);
  useEffect(() => { if (!urlRestored || !Object.keys(matrix).length) return; const params = new URLSearchParams(); params.set("mode", mode); if (a) params.set("parentA", a.id); if (b) params.set("parentB", b.id); if (parent) params.set("parent", parent.id); if (target) params.set("target", target.id); if (start) params.set("starting", start.id); if (max !== 3) params.set("max", String(max)); history.replaceState(null, "", `${location.pathname}?${params}`); }, [mode, a, b, parent, target, start, max, matrix, urlRestored]);
  useEffect(() => { if (urlRestored) saveAvailablePals(available); }, [available, urlRestored]);
  useEffect(() => { if (slot) requestAnimationFrame(() => searchInputRef.current?.focus()); }, [slot]);

  const childResults = useMemo(() => a && b ? pairResults(matrix, byId, a, b) : [], [matrix, byId, a, b]);
  const allPairs = useMemo(() => target ? findParentPairs(matrix, byId, target) : [], [matrix, byId, target]);
  const pairCandidates = useMemo(() => Array.from(new Map(allPairs.flatMap((result) => [result.first, result.second]).map((pal) => [pal.id, pal])).values()).sort(comparePals), [allPairs]);
  const targetPairs = useMemo(() => parentFilter ? allPairs.filter((result) => result.first.id === parentFilter || result.second.id === parentFilter) : allPairs, [allPairs, parentFilter]);
  const allOffspring = useMemo(() => parent ? findOffspring(matrix, byId, parent) : [], [matrix, byId, parent]);
  const offspringCandidates = useMemo(() => Array.from(new Map(allOffspring.flatMap((result) => [result.second, result.child]).map((pal) => [pal.id, pal])).values()).sort(comparePals), [allOffspring]);
  const offspring = useMemo(() => offspringFilter ? allOffspring.filter((result) => result.second.id === offspringFilter || result.child.id === offspringFilter) : allOffspring, [allOffspring, offspringFilter]);
  const now = useMemo(() => availableOffspring(matrix, byId, available), [matrix, byId, available]);
  const route = useMemo(() => target && start ? findRoutes(matrix, byId, [start], target, pals, max, new Set(excluded)) : [], [matrix, byId, target, start, max, excluded]);
  const availableRouteDirty = Boolean(availableRouteQuery && (availableRouteQuery.targetId !== target?.id || availableRouteQuery.max !== max || availableRouteQuery.available.length !== available.length || availableRouteQuery.available.some((id, index) => id !== available[index])));
  const availableRoute = useMemo(() => { if (!availableRouteQuery || availableRouteDirty) return []; const submittedTarget = byId.get(availableRouteQuery.targetId); const submittedPals = availableRouteQuery.available.map((id) => byId.get(id)).filter((pal): pal is PalData => Boolean(pal)); return submittedTarget ? findRoutes(matrix, byId, submittedPals, submittedTarget, submittedPals, availableRouteQuery.max) : []; }, [matrix, byId, availableRouteQuery, availableRouteDirty]);
  const pickerCandidates = slot === "parent-filter" ? pairCandidates : slot === "offspring-filter" ? offspringCandidates : slot === "exclude" ? pals.filter((pal) => !excluded.includes(pal.id)) : pals;
  const search = useMemo(() => { const n = query.trim().toLowerCase(); return pickerCandidates.filter((pal) => (!n || pal.name.toLowerCase().includes(n) || pal.number.toLowerCase().includes(n)) && (!pickerElement || pal.elements.includes(pickerElement)) && (!pickerRarity || String(pal.rarity) === pickerRarity)).sort(comparePals); }, [pickerCandidates, pickerElement, pickerRarity, query]);
  const visibleSearch = search.slice(0, pickerLimit);
  const pickerElements = useMemo(() => Array.from(new Set(pals.flatMap((pal) => pal.elements))).sort(), []);
  const pickerRarities = useMemo(() => Array.from(new Set(pals.map((pal) => pal.rarity).filter((value): value is number => value !== null))).sort((first, second) => first - second), []);
  function openPicker(next: Exclude<Slot, null>, trigger: HTMLElement) { pickerTriggerRef.current = trigger; setPickerLimit(PICKER_BATCH_SIZE); setPickerElement(""); setPickerRarity(""); setSlot(next); }
  function loadMorePicker() { if (pickerLoading) return; setPickerLoading(true); window.setTimeout(() => { setPickerLimit((limit) => limit + PICKER_BATCH_SIZE); setPickerLoading(false); }, 180); }
  function closePicker() { setSlot(embedded ? defaultPickerSlots[mode] : null); setQuery(""); setPickerElement(""); setPickerRarity(""); requestAnimationFrame(() => pickerTriggerRef.current?.focus()); }
  function choose(pal: PalData) { if (slot === "available") { setAvailable((current) => current.includes(pal.id) ? current.filter((id) => id !== pal.id) : [...current, pal.id]); return; } const chosenSlot = slot; if (chosenSlot === "a") setA(pal); if (chosenSlot === "b") setB(pal); if (chosenSlot === "target") { setTarget(pal); setParentFilter(undefined); setTargetVisibleCount(50); setTargetSelectionVersion((version) => version + 1); } if (chosenSlot === "parent") { setParent(pal); setOffspringFilter(undefined); } if (chosenSlot === "start") setStart(pal); if (chosenSlot === "parent-filter") setParentFilter(pal.id); if (chosenSlot === "offspring-filter") setOffspringFilter(pal.id); if (chosenSlot === "exclude") setExcluded((current) => current.includes(pal.id) ? current : [...current, pal.id]); if (embedded) { setQuery(""); setPickerElement(""); setPickerRarity(""); setSlot(chosenSlot === "a" ? "b" : chosenSlot); } else closePicker(); }
  function copy(text: string) { navigator.clipboard?.writeText(text); }

  const pick = (label: string, value: PalData | undefined, next: Exclude<Slot, null>) => <button className={`home-breeding-slot home-selector-card ${value ? "selected" : ""}`} onClick={(event) => openPicker(next, event.currentTarget)}><span className="slot-label">{label}</span><PalMark pal={value} /><strong className="pal-name-display">{value ? <LocalizedPalName pal={value} locale={locale} /> : (t?.choose ?? "Choose a Pal")}</strong><small>{value ? `${t?.no ?? "No."} ${value.number}` : locale === "zh" ? null : (t?.choosePal ?? "Tap to browse all Pals")}</small><i>{value ? (t?.change ?? "Change Pal") : locale === "zh" ? null : (t?.choosePal ?? "Choose Pal")}</i></button>;
  const homeParentPick = (label: string, value: PalData | undefined, next: Extract<Slot, "a" | "b">) => pick(label, value, next);
  const resultFilter = (label: string, value: string | undefined, candidates: PalData[], next: Extract<Slot, "offspring-filter">, clear: () => void) => <div className="home-result-filter"><span>{label}</span><button type="button" className="home-compact-picker" style={{ minHeight: 48, padding: "6px 8px" }} onClick={(event) => openPicker(next, event.currentTarget)}><PalMark pal={value ? byId.get(value) : undefined} small /><span><strong className="pal-name-display">{value && byId.get(value) ? <LocalizedPalName pal={byId.get(value)!} locale={locale} /> : "All Pals"}</strong><em>{value ? `No. ${byId.get(value)?.number}` : `${candidates.length} available`}</em></span><b>{value ? "Change" : "Select"}</b></button>{value && <button type="button" className="home-filter-clear" onClick={clear}>Clear</button>}</div>;
  const parentResultFilter = (label: string, value: string | undefined, candidates: PalData[]) => <div className="home-result-filter"><span>{label}</span><button type="button" className="home-compact-picker" style={{ minHeight: 48, padding: "6px 8px" }} onClick={(event) => openPicker("parent-filter", event.currentTarget)}><PalMark pal={value ? byId.get(value) : undefined} small /><span><strong className="pal-name-display">{value && byId.get(value) ? <LocalizedPalName pal={byId.get(value)!} locale={locale} /> : "All parents"}</strong><em>{value ? `No. ${byId.get(value)?.number}` : `${candidates.length} available`}</em></span><b>{value ? "Change" : "Select"}</b></button>{value && <button type="button" className="home-filter-clear" onClick={() => { setParentFilter(undefined); setTargetVisibleCount(50); }}>Clear</button>}</div>;
  useEffect(() => { if (mode !== "target" || !target || !Object.keys(matrix).length) return; const key = `${target.id}:${targetSelectionVersion}`; if (lastScrolledTargetRef.current === key) return; lastScrolledTargetRef.current = key; requestAnimationFrame(() => { const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; targetResultsRef.current?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" }); }); }, [mode, target, matrix, targetSelectionVersion]);
  const availableRouteResultsRef = useRef<HTMLElement>(null);
  useEffect(() => { if (mode !== "available-route" || !availableRouteQuery || availableRouteDirty || availableRouteLoading || !Object.keys(matrix).length) return; requestAnimationFrame(() => { const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; availableRouteResultsRef.current?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" }); }); }, [mode, availableRouteQuery, availableRouteDirty, availableRouteLoading, availableRouteVersion, matrix]);
  function findAvailableRoutes() { if (!available.length || !target || !Number.isFinite(max) || max < 1) return; setAvailableRouteLoading(true); window.setTimeout(() => { setAvailableRouteQuery({ available: [...available], targetId: target.id, max }); setAvailableRouteVersion((version) => version + 1); setAvailableRouteLoading(false); }, 180); }
  const list = (items: BreedingResult[], empty: string) => items.length ? <div className="breed-list">{items.slice(0, page * 40).map((item, i) => <Result key={`${item.first.id}-${item.second.id}-${item.child.id}-${i}`} result={item} locale={locale} usePair={() => { setA(item.first); setB(item.second); setMode("parents"); }} />)}{items.length > page * 40 && <button onClick={() => setPage(page + 1)}>{t?.loadMore ?? "Load more"}</button>}<div className="breed-database-actions"><DatabaseResultLink pals={items.map((item) => item.child)} locale={locale} /></div></div> : <p className="breed-empty">{empty}</p>;

  const pickerPanel = slot ? <PalPickerPanel embedded={embedded} locale={locale} slot={slot} available={available} search={search} visibleSearch={visibleSearch} pickerLoading={pickerLoading} query={query} element={pickerElement} rarity={pickerRarity} elements={pickerElements} rarities={pickerRarities} searchInputRef={searchInputRef} setQuery={(value) => { setQuery(value); setPickerLimit(PICKER_BATCH_SIZE); }} onElementChange={setPickerElement} onRarityChange={setPickerRarity} onChoose={choose} onClearAvailable={() => setAvailable([])} onClose={closePicker} onLoadMore={loadMorePicker} /> : null;
  if (error) return <section className={`database-workspace${embedded ? " home-breeding-workspace" : ""}`}><p>{t?.error ?? "Breeding data is unavailable."} <button onClick={() => location.reload()}>{t?.retry ?? "Retry"}</button></p></section>;
  return <section className={`database-workspace breeding-workspace${embedded ? " home-breeding-workspace" : ""}${locale === "zh" ? " zh-calculator" : ""}`} aria-label="Palworld breeding calculator controls">
    <nav className="home-breeding-tabs" aria-label={locale === "zh" ? "配种工具" : "Breeding tools"}>{modes.map(([id]) => <button key={id} className={mode === id ? "active" : ""} aria-pressed={mode === id} onClick={() => { setMode(id); setPage(1); setQuery(""); setPickerElement(""); setPickerRarity(""); if (embedded) setSlot(defaultPickerSlots[id]); else setSlot(null); }}>{modeLabels[id]}</button>)}</nav>
    <p className="home-mode-description" aria-live="polite">{modeCopy[mode]}</p>
    <div className="home-breeding-card home-workbench"><div className="breeding-card-glow" />
      {mode === "parents" && <><div className="home-breeding-equation">{homeParentPick(locale === "zh" ? "父母 A" : "Parent A", a, "a")}<b className="breeding-operator">+</b>{homeParentPick(locale === "zh" ? "父母 B" : "Parent B", b, "b")}<b className="breeding-operator equals">=</b><div className={`home-breeding-slot offspring ${childResults.length ? "selected" : "empty"}`}><span className="slot-label">{t?.offspring ?? "Offspring"}</span>{childResults[0] ? <PalMark pal={childResults[0].child} /> : <span className="offspring-empty-mark" aria-hidden="true"><svg viewBox="0 0 84 92" focusable="false"><path d="M42 5C24 5 10 25 10 48c0 24 13 39 32 39s32-15 32-39C74 25 60 5 42 5Z" /><path d="M27 28c4-6 9-10 15-11M23 42c1-4 2-7 4-10" /></svg></span>}<strong className="pal-name-display">{childResults[0] ? <LocalizedPalName pal={childResults[0].child} locale={locale} /> : (t?.offspring ?? "Offspring result")}</strong><small>{childResults[0] ? `${t?.no ?? "No."} ${childResults[0].child.number}` : (t?.chooseBoth ?? "Choose both parents to calculate")}</small><i>{childResults[0] ? (t?.result ?? "Breeding result") : (t?.waiting ?? "Waiting for parents")}</i>{childResults.length === 1 && <DatabaseResultLink pals={[childResults[0].child]} locale={locale} />}</div></div>{childResults.length > 1 && <section className="home-results"><header><span>{t?.results ?? "Results"}</span><strong>{childResults.length} {t?.outcomes ?? "outcomes"}</strong></header><div className="result-card-details">{childResults.map((result, index) => <Result key={`${result.child.id}-${index}`} result={result} locale={locale} />)}</div><div className="breed-database-actions"><DatabaseResultLink pals={childResults.map((result) => result.child)} locale={locale} /></div></section>}{a && b && !childResults.length && <p className="breed-empty">{t?.noResult ?? "No breeding result was found."}</p>}<div className="calculator-foot">{locale !== "zh" && <button onClick={() => { setA(b); setB(a); }}>{t?.swap ?? "Swap"}</button>}<button onClick={() => { setA(undefined); setB(undefined); }}>{t?.clear ?? "Clear"}</button>{childResults.length > 0 && <button onClick={() => copy(childResults.map((r) => `${r.first.name} + ${r.second.name} → ${r.child.name}`).join("\n"))}>{t?.copyCombination ?? "Copy combination"}</button>}</div></>}
      {mode === "target" && <><div className="home-control-row">{pick(t?.target ?? "Target Pal", target, "target")}</div>{target && <section ref={targetResultsRef} className="home-results target-results"><header><div><span>{t?.parentCombinations ?? "Parent Combinations"}</span><strong>{targetPairs.length} {t?.found ?? "found"}</strong></div>{allPairs.length > 0 && parentResultFilter(t?.filterParent ?? "Filter by Parent", parentFilter, pairCandidates)}</header>{targetPairs.length ? <><p className="home-results-count">{t?.showing ?? "Showing"} 1–{Math.min(targetVisibleCount, targetPairs.length)} / {targetPairs.length} {t?.combinations ?? "combinations"}</p><div className="breed-list">{targetPairs.slice(0, targetVisibleCount).map((item, index) => <Result key={`${item.first.id}-${item.second.id}-${index}`} result={item} locale={locale} showDatabaseLink />)}</div>{targetVisibleCount < targetPairs.length ? <button type="button" onClick={() => setTargetVisibleCount((count) => Math.min(count + 50, targetPairs.length))}>{t?.loadMore ?? "Load more"}</button> : <p className="breed-empty">{t?.allShown ?? "All combinations shown"}</p>}</> : <p className="breed-empty">{locale === "zh" ? "没有找到这个帕鲁的父母组合。" : "No parent combinations found for this Pal."}</p>}</section>}</>}
      {mode === "offspring" && <><div className="home-control-row">{pick(locale === "zh" ? "已选父母" : "Selected Parent", parent, "parent")}</div><section className="home-results"><header><div><span>{locale === "zh" ? "可配出的子代" : "Possible offspring"}</span><strong>{parent ? `${offspring.length} ${t?.found ?? "found"}` : (t?.chooseParent ?? "Select a parent")}</strong></div>{parent && allOffspring.length > 0 && resultFilter(locale === "zh" ? "筛选结果" : "Filter results", offspringFilter, offspringCandidates, "offspring-filter", () => setOffspringFilter(undefined))}</header>{list(offspring, t?.chooseParent ?? "Choose a parent to see all offspring.")}</section></>}
      {mode === "available" && <><Available pals={pals} available={available} setAvailable={setAvailable} openPicker={openPicker} locale={locale} /><section className="home-results"><header><span>{t?.breedNow ?? "Breed now"}</span><strong>{now.length} {t?.offspring ?? "offspring"} · {available.length} {t?.selected ?? "selected"}</strong></header>{now.length ? <><div className="breed-list">{now.map(({ child, combinations }) => <details key={child.id}><summary><PalMark pal={child} small /><LocalizedPalName pal={child} locale={locale} /> · {combinations.length} {t?.combinations ?? "combinations"}</summary>{combinations.map((r, i) => <Result key={i} result={r} locale={locale} />)}</details>)}</div><div className="breed-database-actions"><DatabaseResultLink pals={now.map((item) => item.child)} locale={locale} /></div></> : <p className="breed-empty">{t?.addToSee ?? "Add available Pals to see the offspring you can breed now."}</p>}</section></>}
      {mode === "shortest" && <><div className="home-route-controls">{pick(t?.start ?? "Starting Pal", start, "start")}{pick(t?.target ?? "Target Pal", target, "target")}<GenerationSelect value={max} onChange={setMax} locale={locale} /></div><details className="home-advanced-options"><summary>{t?.advanced ?? "Advanced options"}</summary><div><span>{t?.exclude ?? "Exclude Pals"}</span><button type="button" className="home-advanced-add" onClick={(event) => openPicker("exclude", event.currentTarget)}>+ {t?.selectPals ?? "Select Pals"}</button>{excluded.length > 0 && <button type="button" className="home-filter-clear" onClick={() => setExcluded([])}>{t?.clearAll ?? "Clear all"}</button>}<section className="home-excluded-tags">{excluded.map((id) => { const pal = byId.get(id); return pal ? <button type="button" key={id} onClick={() => setExcluded((current) => current.filter((entry) => entry !== id))}><PalMark pal={pal} small /><LocalizedPalName pal={pal} locale={locale} /><span>×</span></button> : null; })}</section></div></details><section className="home-results"><header><span>{t?.routeResults ?? "Route results"}</span><strong>{target ? `${t?.upTo ?? "Up to"} ${max} ${t?.generations ?? "generations"}` : (t?.selectTarget ?? "Set a target")}</strong></header>{!start || !target ? <p className="breed-empty">{t?.chooseRouteInputs ?? "Choose a starting Pal and a target Pal to calculate a route."}</p> : <Routes routes={route} copy={copy} locale={locale} />}</section></>}
      {mode === "available-route" && <><div className="home-route-controls"><Available pals={pals} available={available} setAvailable={setAvailable} openPicker={openPicker} compact manualRoute locale={locale} />{pick(t?.target ?? "Target Pal", target, "target")}<GenerationSelect value={max} onChange={setMax} locale={locale} /></div><div className="home-route-submit"><button type="button" disabled={!available.length || !target || !Number.isFinite(max) || max < 1 || availableRouteLoading} onClick={findAvailableRoutes}>{availableRouteLoading ? (t?.finding ?? "Finding breeding routes...") : (t?.findRoutes ?? "Find Breeding Routes")}</button>{!available.length ? <p>{locale === "zh" ? "至少选择一个已有帕鲁。" : "Select at least one Pal you own."}</p> : !target ? <p>{t?.selectTarget ?? "Choose a target Pal."}</p> : availableRouteDirty ? <p>{t?.inputsChanged ?? "Inputs changed. Find breeding routes again."}</p> : null}</div><section ref={availableRouteResultsRef} className="home-results route-results"><header><span>{t?.routeResults ?? "Route results"}</span><strong>{availableRouteQuery && !availableRouteDirty ? `${t?.upTo ?? "Up to"} ${availableRouteQuery.max} ${t?.generations ?? "generations"}` : (t?.runSearch ?? "Run a search to see routes")}</strong></header>{availableRouteLoading ? <p className="breed-empty">{t?.finding ?? "Finding breeding routes..."}</p> : availableRouteDirty ? <p className="breed-empty">{t?.inputsChanged ?? "Inputs changed. Find breeding routes again."}</p> : availableRouteQuery ? availableRoute.length ? <Routes routes={availableRoute} copy={copy} locale={locale} /> : <p className="breed-empty">{t?.noRoute ?? "No route found within the selected generation limit."}</p> : <p className="breed-empty">{locale === "zh" ? "选择已有帕鲁、目标帕鲁和最大代数，然后查找路线。" : "Choose your owned Pals, target, and maximum generations, then find routes."}</p>}</section></>}
    </div>
    {slot && (embedded ? pickerPanel : <div className={`pal-picker-backdrop${locale === "zh" ? " zh-picker-backdrop" : ""}`} onClick={closePicker}>{pickerPanel}</div>)}
  </section>;
}

function Available({ pals, available, setAvailable, openPicker, compact = false, manualRoute = false, locale = "en" }: { pals: PalData[]; available: string[]; setAvailable: (ids: string[]) => void; openPicker?: (slot: "available", trigger: HTMLElement) => void; compact?: boolean; manualRoute?: boolean; locale?: Locale }) {
  const t = locale === "zh" ? zh.breeding : undefined;
  if (manualRoute) return <section className={`home-breeding-slot home-available-control compact manual-owned-control${locale === "zh" ? " zh-manual-owned-control" : ""}`}><div className="manual-owned-main" role="button" tabIndex={0} aria-label={available.length ? (t?.edit ?? "Edit owned Pals") : (t?.selectOwned ?? "Select owned Pals")} onClick={(event) => openPicker?.("available", event.currentTarget)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openPicker?.("available", event.currentTarget); } }}>{locale === "zh" ? <strong>{available.length ? `已有 ${available.length} 个帕鲁` : "选择已有帕鲁"}</strong> : <><span className="slot-label">{t?.owned ?? "Pals You Own"}</span><strong>{available.length ? `${available.length} ${t?.selected ?? "Pals selected"}` : (t?.selectOwned ?? "Select the Pals you already own")}</strong></>}{available.length ? <span className="manual-owned-preview">{available.slice(0, 4).map((id) => { const pal = pals.find((item) => item.id === id); return pal ? <PalMark key={id} pal={pal} small /> : null; })}{available.length > 4 && <b>+{available.length - 4}</b>}</span> : locale !== "zh" && <small>{t?.selectOwned ?? "Select Owned Pals"}</small>}</div><div className="manual-owned-actions">{available.length > 0 && <button type="button" onClick={() => openPicker?.("available", document.querySelector(".manual-owned-main") as HTMLElement)}>{t?.edit ?? "Edit"}</button>}{available.length > 0 && <button type="button" onClick={() => setAvailable([])}>{t?.clear ?? "Clear"}</button>}</div></section>;
  return <section className={`home-breeding-slot home-available-control${compact ? " compact" : ""}`} role="button" tabIndex={0} aria-label={available.length ? (t?.edit ?? "Edit available Pals") : (t?.choose ?? "Choose available Pals")} onClick={(event) => openPicker?.("available", event.currentTarget)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openPicker?.("available", event.currentTarget); } }}><span className="slot-label">{t?.available ?? "Available Pals"}</span><PalMark /><strong>{available.length ? `${available.length} ${t?.selected ?? "selected"}` : (t?.choose ?? "Choose available Pals")}</strong><small>{available.length ? (t?.savedRoster ?? "Your saved breeding roster") : (t?.addOwned ?? "Add the Pals you can breed with")}</small><i>{available.length ? (t?.change ?? "Change Pals") : (t?.choosePal ?? "Choose Pal")}</i></section>;
}

function Routes({ routes, copy, locale = "en" }: { routes: ReturnType<typeof findRoutes>; copy: (value: string) => void; locale?: Locale }) {
  const t = locale === "zh" ? zh.breeding : undefined;
  if (!routes.length) return <p className="breed-empty">{t?.noRoute ?? "No route found within this generation limit. Adjust the available Pals or maximum generations."}</p>;
  return <div className="route-list">{routes.map((route, i) => <article key={i}><header><strong>{route.generations} {t?.generations ?? "generations"}</strong><button onClick={() => copy(route.steps.map((s, n) => `${t?.step ?? "Step"} ${n + 1}: ${palLabel(s.first, locale)} + ${palLabel(s.second, locale)} → ${palLabel(s.child, locale)}`).join("\n"))}>{t?.copyRoute ?? "Copy Route"}</button><button onClick={() => copy(location.href)}>{t?.copyLink ?? "Copy Link"}</button></header>{route.generations === 0 ? <p>{t?.targetAlready ?? "Target already available · 0 generations"}</p> : route.steps.map((step, n) => <div key={n}><b>{t?.step ?? "Step"} {n + 1}</b><Result result={step} locale={locale} /></div>)}</article>)}</div>;
}
