"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import PalMark from "../components/pal-mark";
import { BreedingData, PalData, pals } from "../lib/game-data";
import { assetUrl } from "../lib/assets";
import { availableOffspring, comparePals, findOffspring, findParentPairs, findRoutes, pairResults, type BreedingResult } from "./breeding/core";
import { readAvailablePals, saveAvailablePals } from "./breeding/storage";

type Mode = "parents" | "target" | "offspring" | "available-route" | "shortest" | "available";
type Slot = "a" | "b" | "target" | "parent" | "start" | "parent-filter" | "offspring-filter" | "exclude" | "available" | null;
const modes: [Mode, string][] = [["parents", "Parents → Child"], ["target", "Target → Parents"], ["offspring", "One Parent → Offspring"], ["available-route", "Owned Pals → Target"], ["shortest", "Shortest Route"], ["available", "What Can I Breed Now"]];
const modeDescriptions: Record<Mode, string> = { parents: "Pick two Pals to see their offspring.", target: "Choose a Pal to reveal every direct parent pair.", offspring: "See every result a selected parent can create.", "available-route": "Select the Pals you own and find a breeding route to your target.", shortest: "Find the fewest breeding steps to your target.", available: "See what your Available Pals can breed now." };
const PICKER_BATCH_SIZE = 60;

function Result({ result, usePair, showDatabaseLink = false }: { result: BreedingResult; usePair?: () => void; showDatabaseLink?: boolean }) {
  return <article className="breed-row"><span><PalMark pal={result.first} small />{result.genders?.[0] && <em>{result.genders[0]}</em>}<Link href={`/pals/${result.first.slug}`}>{result.first.name}</Link></span><b>+</b><span><PalMark pal={result.second} small />{result.genders?.[1] && <em>{result.genders[1]}</em>}<Link href={`/pals/${result.second.slug}`}>{result.second.name}</Link></span><b>→</b><span><PalMark pal={result.child} small /><Link href={`/pals/${result.child.slug}`}>{result.child.name}</Link></span>{result.genders && <small>Gender-specific result</small>}{result.requiresTwo && <small>Requires two compatible individuals</small>}{showDatabaseLink && <DatabaseResultLink pals={[result.first, result.second, result.child]} />}{usePair && <button onClick={usePair}>Use pair</button>}</article>;
}

function DatabaseResultLink({ pals: resultPals }: { pals: PalData[] }) {
  const slugs = Array.from(new Set(resultPals.map((pal) => pal.slug).filter((slug) => pals.some((pal) => pal.slug === slug))));
  if (!slugs.length) return null;
  const href = slugs.length === 1 ? `/pals/${slugs[0]}` : `/pals?ids=${slugs.join(",")}`;
  return <Link className="breed-database-link" href={href}>{slugs.length === 1 ? "View Pal Details" : `View ${slugs.length} Pals in Database`}</Link>;
}

function GenerationSelect({ value, onChange }: { value: number; onChange: (value: number) => void }) {
  const [open, setOpen] = useState(false);
  const controlRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    const close = (event: MouseEvent) => { if (!controlRef.current?.contains(event.target as Node)) setOpen(false); };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, [open]);
  return <div ref={controlRef} className="home-number-control"><span>Maximum generations</span><button type="button" className="home-generation-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((current) => !current)}><strong>{value}</strong><b aria-hidden="true">⌄</b></button>{open && <div className="home-generation-menu" role="listbox" aria-label="Maximum generations">{[1, 2, 3, 4, 5].map((generation) => <button type="button" role="option" aria-selected={generation === value} className={generation === value ? "selected" : ""} key={generation} onClick={() => { onChange(generation); setOpen(false); }}>{generation}</button>)}</div>}</div>;
}

export default function BreedingClient({ embedded = false }: { embedded?: boolean }) {
  const [matrix, setMatrix] = useState<BreedingData>({});
  const [error, setError] = useState(false);
  const [mode, setMode] = useState<Mode>("parents");
  const [a, setA] = useState<PalData | undefined>();
  const [b, setB] = useState<PalData | undefined>();
  const [target, setTarget] = useState<PalData | undefined>();
  const [parent, setParent] = useState<PalData | undefined>();
  const [start, setStart] = useState<PalData | undefined>();
  const [slot, setSlot] = useState<Slot>(null);
  const [query, setQuery] = useState("");
  const [pickerLimit, setPickerLimit] = useState(PICKER_BATCH_SIZE);
  const [pickerLoading, setPickerLoading] = useState(false);
  const [available, setAvailable] = useState<string[]>([]);
  const [max, setMax] = useState(3);
  const [excluded, setExcluded] = useState<string[]>([]);
  const [parentFilter, setParentFilter] = useState<string | undefined>();
  const [offspringFilter, setOffspringFilter] = useState<string | undefined>();
  const [page, setPage] = useState(1);
  const [targetVisibleCount, setTargetVisibleCount] = useState(50);
  const [targetSelectionVersion, setTargetSelectionVersion] = useState(0);
  const [availableRouteQuery, setAvailableRouteQuery] = useState<{ available: string[]; targetId: string; max: number } | null>(null);
  const [availableRouteLoading, setAvailableRouteLoading] = useState(false);
  const [availableRouteVersion, setAvailableRouteVersion] = useState(0);
  const [urlRestored, setUrlRestored] = useState(false);
  const searchInputRef = useRef<HTMLInputElement>(null);
  const pickerTriggerRef = useRef<HTMLElement | null>(null);
  const targetResultsRef = useRef<HTMLElement>(null);
  const lastScrolledTargetRef = useRef<string | undefined>(undefined);
  const byId = useMemo(() => new Map(pals.map((pal) => [pal.id, pal])), []);

  useEffect(() => { fetch(assetUrl("/data/breeding.json")).then((r) => r.ok ? r.json() : Promise.reject()).then(setMatrix).catch(() => setError(true)); }, []);
  useEffect(() => { const frame = requestAnimationFrame(() => { const params = new URLSearchParams(window.location.search); const requestedMode = params.get("mode"); const palFromParam = (name: string) => pals.find((pal) => pal.id === params.get(name)); if (modes.some(([id]) => id === requestedMode)) setMode(requestedMode as Mode); setA(palFromParam("parentA")); setB(palFromParam("parentB")); setTarget(palFromParam("target")); setParent(palFromParam("parent")); setStart(palFromParam("starting")); setMax(Math.min(5, Math.max(1, Number(params.get("max")) || 3))); setAvailable(readAvailablePals()); setUrlRestored(true); }); return () => cancelAnimationFrame(frame); }, []);
  useEffect(() => { if (!urlRestored || !Object.keys(matrix).length) return; const params = new URLSearchParams(); params.set("mode", mode); if (a) params.set("parentA", a.id); if (b) params.set("parentB", b.id); if (parent) params.set("parent", parent.id); if (target) params.set("target", target.id); if (start) params.set("starting", start.id); if (max !== 3) params.set("max", String(max)); history.replaceState(null, "", `${location.pathname}?${params}`); }, [mode, a, b, parent, target, start, max, matrix, urlRestored]);
  useEffect(() => { if (urlRestored) saveAvailablePals(available); }, [available, urlRestored]);
  useEffect(() => { if (slot) requestAnimationFrame(() => searchInputRef.current?.focus()); }, [slot]);

  const childResults = useMemo(() => a && b ? pairResults(matrix, byId, a, b) : [], [matrix, byId, a, b]);
  const allPairs = useMemo(() => target ? findParentPairs(matrix, byId, target) : [], [matrix, byId, target]);
  const pairCandidates = useMemo(() => Array.from(new Map(allPairs.flatMap((result) => [result.first, result.second]).map((pal) => [pal.id, pal])).values()).sort(comparePals), [allPairs]);
  const targetPairs = useMemo(() => parentFilter ? allPairs.filter((result) => result.first.id === parentFilter || result.second.id === parentFilter) : allPairs, [allPairs, parentFilter]);
  const allOffspring = useMemo(() => parent ? findOffspring(matrix, byId, parent) : [], [matrix, byId, parent]);
  const offspringCandidates = useMemo(() => Array.from(new Map(allOffspring.flatMap((result) => [result.second, result.child]).map((pal) => [pal.id, pal])).values()).sort(comparePals), [allOffspring]);
  const offspring = useMemo(() => offspringFilter ? allOffspring.filter((result) => result.second.id === offspringFilter || result.child.id === offspringFilter) : allOffspring, [allOffspring, offspringFilter]);
  const now = useMemo(() => availableOffspring(matrix, byId, available), [matrix, byId, available]);
  const route = useMemo(() => target && start ? findRoutes(matrix, byId, [start], target, pals, max, new Set(excluded)) : [], [matrix, byId, target, start, max, excluded]);
  const availableRouteDirty = Boolean(availableRouteQuery && (availableRouteQuery.targetId !== target?.id || availableRouteQuery.max !== max || availableRouteQuery.available.length !== available.length || availableRouteQuery.available.some((id, index) => id !== available[index])));
  const availableRoute = useMemo(() => { if (!availableRouteQuery || availableRouteDirty) return []; const submittedTarget = byId.get(availableRouteQuery.targetId); const submittedPals = availableRouteQuery.available.map((id) => byId.get(id)).filter((pal): pal is PalData => Boolean(pal)); return submittedTarget ? findRoutes(matrix, byId, submittedPals, submittedTarget, submittedPals, availableRouteQuery.max) : []; }, [matrix, byId, availableRouteQuery, availableRouteDirty]);
  const pickerCandidates = slot === "parent-filter" ? pairCandidates : slot === "offspring-filter" ? offspringCandidates : slot === "exclude" ? pals.filter((pal) => !excluded.includes(pal.id)) : pals;
  const search = useMemo(() => { const n = query.trim().toLowerCase(); return pickerCandidates.filter((pal) => !n || pal.name.toLowerCase().includes(n) || pal.number.toLowerCase().includes(n)).sort(comparePals); }, [pickerCandidates, query]);
  const visibleSearch = search.slice(0, pickerLimit);
  function openPicker(next: Exclude<Slot, null>, trigger: HTMLElement) { pickerTriggerRef.current = trigger; setPickerLimit(PICKER_BATCH_SIZE); setSlot(next); }
  function loadMorePicker() { if (pickerLoading) return; setPickerLoading(true); window.setTimeout(() => { setPickerLimit((limit) => limit + PICKER_BATCH_SIZE); setPickerLoading(false); }, 180); }
  function closePicker() { setSlot(null); setQuery(""); requestAnimationFrame(() => pickerTriggerRef.current?.focus()); }
  function choose(pal: PalData) { if (slot === "available") { setAvailable((current) => current.includes(pal.id) ? current.filter((id) => id !== pal.id) : [...current, pal.id]); return; } if (slot === "a") setA(pal); if (slot === "b") setB(pal); if (slot === "target") { setTarget(pal); setParentFilter(undefined); setTargetVisibleCount(50); setTargetSelectionVersion((version) => version + 1); } if (slot === "parent") { setParent(pal); setOffspringFilter(undefined); } if (slot === "start") setStart(pal); if (slot === "parent-filter") setParentFilter(pal.id); if (slot === "offspring-filter") setOffspringFilter(pal.id); if (slot === "exclude") setExcluded((current) => current.includes(pal.id) ? current : [...current, pal.id]); closePicker(); }
  function copy(text: string) { navigator.clipboard?.writeText(text); }

  const pick = (label: string, value: PalData | undefined, next: Exclude<Slot, null>) => <button className={`home-breeding-slot home-selector-card ${value ? "selected" : ""}`} onClick={(event) => openPicker(next, event.currentTarget)}><span className="slot-label">{label}</span><PalMark pal={value} /><strong>{value?.name ?? "Choose a Pal"}</strong><small>{value ? `No. ${value.number}` : "Tap to browse all Pals"}</small><i>{value ? "Change Pal" : "Choose Pal"}</i></button>;
  const homeParentPick = (label: string, value: PalData | undefined, next: Extract<Slot, "a" | "b">) => pick(label, value, next);
  const resultFilter = (label: string, value: string | undefined, candidates: PalData[], next: Extract<Slot, "offspring-filter">, clear: () => void) => <div className="home-result-filter"><span>{label}</span><button type="button" className="home-compact-picker" style={{ minHeight: 48, padding: "6px 8px" }} onClick={(event) => openPicker(next, event.currentTarget)}><PalMark pal={value ? byId.get(value) : undefined} small /><span><strong>{value ? byId.get(value)?.name : "All Pals"}</strong><em>{value ? `No. ${byId.get(value)?.number}` : `${candidates.length} available`}</em></span><b>{value ? "Change" : "Select"}</b></button>{value && <button type="button" className="home-filter-clear" onClick={clear}>Clear</button>}</div>;
  const parentResultFilter = (label: string, value: string | undefined, candidates: PalData[]) => <div className="home-result-filter"><span>{label}</span><button type="button" className="home-compact-picker" style={{ minHeight: 48, padding: "6px 8px" }} onClick={(event) => openPicker("parent-filter", event.currentTarget)}><PalMark pal={value ? byId.get(value) : undefined} small /><span><strong>{value ? byId.get(value)?.name : "All parents"}</strong><em>{value ? `No. ${byId.get(value)?.number}` : `${candidates.length} available`}</em></span><b>{value ? "Change" : "Select"}</b></button>{value && <button type="button" className="home-filter-clear" onClick={() => { setParentFilter(undefined); setTargetVisibleCount(50); }}>Clear</button>}</div>;
  useEffect(() => { if (mode !== "target" || !target || !Object.keys(matrix).length) return; const key = `${target.id}:${targetSelectionVersion}`; if (lastScrolledTargetRef.current === key) return; lastScrolledTargetRef.current = key; requestAnimationFrame(() => { const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; targetResultsRef.current?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" }); }); }, [mode, target, matrix, targetSelectionVersion]);
  const availableRouteResultsRef = useRef<HTMLElement>(null);
  useEffect(() => { if (mode !== "available-route" || !availableRouteQuery || availableRouteDirty || availableRouteLoading || !Object.keys(matrix).length) return; requestAnimationFrame(() => { const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches; availableRouteResultsRef.current?.scrollIntoView({ behavior: reduced ? "auto" : "smooth", block: "start" }); }); }, [mode, availableRouteQuery, availableRouteDirty, availableRouteLoading, availableRouteVersion, matrix]);
  function findAvailableRoutes() { if (!available.length || !target || !Number.isFinite(max) || max < 1) return; setAvailableRouteLoading(true); window.setTimeout(() => { setAvailableRouteQuery({ available: [...available], targetId: target.id, max }); setAvailableRouteVersion((version) => version + 1); setAvailableRouteLoading(false); }, 180); }
  const list = (items: BreedingResult[], empty: string) => items.length ? <div className="breed-list">{items.slice(0, page * 40).map((item, i) => <Result key={`${item.first.id}-${item.second.id}-${item.child.id}-${i}`} result={item} usePair={() => { setA(item.first); setB(item.second); setMode("parents"); }} />)}{items.length > page * 40 && <button onClick={() => setPage(page + 1)}>Load more</button>}<div className="breed-database-actions"><DatabaseResultLink pals={items.map((item) => item.child)} /></div></div> : <p className="breed-empty">{empty}</p>;

  if (error) return <section className={`database-workspace${embedded ? " home-breeding-workspace" : ""}`}><p>Breeding data is unavailable. <button onClick={() => location.reload()}>Retry</button></p></section>;
  return <section className={`database-workspace breeding-workspace${embedded ? " home-breeding-workspace" : ""}`} aria-label="Palworld breeding calculator controls">
    <nav className="home-breeding-tabs" aria-label="Breeding tools">{modes.map(([id, label]) => <button key={id} className={mode === id ? "active" : ""} aria-pressed={mode === id} onClick={() => { setMode(id); setPage(1); }}>{label}</button>)}</nav>
    <p className="home-mode-description" aria-live="polite">{modeDescriptions[mode]}</p>
    <div className="home-breeding-card home-workbench"><div className="breeding-card-glow" />
      {mode === "parents" && <><div className="home-breeding-equation">{homeParentPick("Parent A", a, "a")}<b className="breeding-operator">+</b>{homeParentPick("Parent B", b, "b")}<b className="breeding-operator equals">=</b><div className={`home-breeding-slot offspring ${childResults.length ? "selected" : "empty"}`}><span className="slot-label">Offspring</span>{childResults[0] ? <PalMark pal={childResults[0].child} /> : <span className="offspring-empty-mark" aria-hidden="true"><svg viewBox="0 0 84 92" focusable="false"><path d="M42 5C24 5 10 25 10 48c0 24 13 39 32 39s32-15 32-39C74 25 60 5 42 5Z" /><path d="M27 28c4-6 9-10 15-11M23 42c1-4 2-7 4-10" /></svg></span>}<strong>{childResults[0]?.child.name ?? "Offspring result"}</strong><small>{childResults[0] ? `No. ${childResults[0].child.number}` : "Choose both parents to calculate"}</small><i>{childResults[0] ? "Breeding result" : "Waiting for parents"}</i>{childResults.length === 1 && <DatabaseResultLink pals={[childResults[0].child]} />}</div></div>{childResults.length > 1 && <section className="home-results"><header><span>Results</span><strong>{childResults.length} outcomes</strong></header><div className="result-card-details">{childResults.map((result, index) => <Result key={`${result.child.id}-${index}`} result={result} />)}</div><div className="breed-database-actions"><DatabaseResultLink pals={childResults.map((result) => result.child)} /></div></section>}{a && b && !childResults.length && <p className="breed-empty">No breeding result was found.</p>}<div className="calculator-foot"><button onClick={() => { setA(b); setB(a); }}>Swap</button><button onClick={() => { setA(undefined); setB(undefined); }}>Clear</button>{childResults.length > 0 && <button onClick={() => copy(childResults.map((r) => `${r.first.name} + ${r.second.name} → ${r.child.name}`).join("\n"))}>Copy combination</button>}</div></>}
      {mode === "target" && <><div className="home-control-row">{pick("Target Pal", target, "target")}</div>{target && <section ref={targetResultsRef} className="home-results target-results"><header><div><span>Parent Combinations</span><strong>{targetPairs.length} found</strong></div>{allPairs.length > 0 && parentResultFilter("Filter by Parent", parentFilter, pairCandidates)}</header>{targetPairs.length ? <><p className="home-results-count">Showing 1–{Math.min(targetVisibleCount, targetPairs.length)} of {targetPairs.length} combinations</p><div className="breed-list">{targetPairs.slice(0, targetVisibleCount).map((item, index) => <Result key={`${item.first.id}-${item.second.id}-${index}`} result={item} showDatabaseLink />)}</div>{targetVisibleCount < targetPairs.length ? <button type="button" onClick={() => setTargetVisibleCount((count) => Math.min(count + 50, targetPairs.length))}>Load {Math.min(50, targetPairs.length - targetVisibleCount)} More</button> : <p className="breed-empty">All {targetPairs.length} combinations shown</p>}</> : <p className="breed-empty">No parent combinations found for this Pal.</p>}</section>}</>}
      {mode === "offspring" && <><div className="home-control-row">{pick("Selected Parent", parent, "parent")}</div><section className="home-results"><header><div><span>Possible offspring</span><strong>{parent ? `${offspring.length} found` : "Select a parent"}</strong></div>{parent && allOffspring.length > 0 && resultFilter("Filter results", offspringFilter, offspringCandidates, "offspring-filter", () => setOffspringFilter(undefined))}</header>{list(offspring, "Choose a parent to see all offspring.")}</section></>}
      {mode === "available" && <><Available pals={pals} available={available} setAvailable={setAvailable} openPicker={openPicker} /><section className="home-results"><header><span>Breed now</span><strong>{now.length} offspring · {available.length} selected</strong></header>{now.length ? <><div className="breed-list">{now.map(({ child, combinations }) => <details key={child.id}><summary><PalMark pal={child} small />{child.name} · {combinations.length} combinations</summary>{combinations.map((r, i) => <Result key={i} result={r} />)}</details>)}</div><div className="breed-database-actions"><DatabaseResultLink pals={now.map((item) => item.child)} /></div></> : <p className="breed-empty">Add available Pals to see the offspring you can breed now.</p>}</section></>}
      {mode === "shortest" && <><div className="home-route-controls">{pick("Starting Pal", start, "start")}{pick("Target Pal", target, "target")}<GenerationSelect value={max} onChange={setMax} /></div><details className="home-advanced-options"><summary>Advanced options</summary><div><span>Exclude Pals</span><button type="button" className="home-advanced-add" onClick={(event) => openPicker("exclude", event.currentTarget)}>+ Select Pals</button>{excluded.length > 0 && <button type="button" className="home-filter-clear" onClick={() => setExcluded([])}>Clear all</button>}<section className="home-excluded-tags">{excluded.map((id) => { const pal = byId.get(id); return pal ? <button type="button" key={id} onClick={() => setExcluded((current) => current.filter((entry) => entry !== id))}><PalMark pal={pal} small /><span>{pal.name} ×</span></button> : null; })}</section></div></details><section className="home-results"><header><span>Route results</span><strong>{target ? `Up to ${max} generations` : "Set a target"}</strong></header>{!start || !target ? <p className="breed-empty">Choose a starting Pal and a target Pal to calculate a route.</p> : <Routes routes={route} copy={copy} />}</section></>}
      {mode === "available-route" && <><div className="home-route-controls"><Available pals={pals} available={available} setAvailable={setAvailable} openPicker={openPicker} compact manualRoute />{pick("Target Pal", target, "target")}<GenerationSelect value={max} onChange={setMax} /></div><div className="home-route-submit"><button type="button" disabled={!available.length || !target || !Number.isFinite(max) || max < 1 || availableRouteLoading} onClick={findAvailableRoutes}>{availableRouteLoading ? "Finding breeding routes..." : "Find Breeding Routes"}</button>{!available.length ? <p>Select at least one Pal you own.</p> : !target ? <p>Choose a target Pal.</p> : availableRouteDirty ? <p>Inputs changed. Find breeding routes again.</p> : null}</div><section ref={availableRouteResultsRef} className="home-results route-results"><header><span>Route results</span><strong>{availableRouteQuery && !availableRouteDirty ? `Up to ${availableRouteQuery.max} generations` : "Run a search to see routes"}</strong></header>{availableRouteLoading ? <p className="breed-empty">Finding breeding routes...</p> : availableRouteDirty ? <p className="breed-empty">Inputs changed. Find breeding routes again.</p> : availableRouteQuery ? availableRoute.length ? <Routes routes={availableRoute} copy={copy} /> : <p className="breed-empty">No route found within the selected generation limit.</p> : <p className="breed-empty">Choose your owned Pals, target, and maximum generations, then find routes.</p>}</section></>}
    </div>
    {slot && <div className={`pal-picker-backdrop${embedded ? " home-picker-backdrop" : ""}`} onClick={closePicker}><section className={`pal-picker${embedded ? " home-pal-picker" : ""}`} role="dialog" aria-modal="true" aria-labelledby="pal-selector-title" onClick={(e) => e.stopPropagation()} onKeyDown={(e) => { if (e.key === "Escape") { e.preventDefault(); closePicker(); } }}><header><h2 id="pal-selector-title">Choose a Pal</h2><div>{slot === "available" && available.length > 0 && <button type="button" className="pal-picker-clear" onClick={() => setAvailable([])}>Clear selected</button>}<button type="button" aria-label="Close Pal selector" onClick={closePicker}>×</button></div></header><input ref={searchInputRef} value={query} onChange={(e) => { setQuery(e.target.value); setPickerLimit(PICKER_BATCH_SIZE); }} onKeyDown={(e) => { if (e.key === "Enter" && search[0]) choose(search[0]); }} placeholder="Search name or Paldeck number…" aria-label="Search Pals by name or Paldeck number" /><p className="pal-picker-progress">Showing {visibleSearch.length} of {search.length} Pals</p><div className="pal-picker-grid">{visibleSearch.map((pal) => <button key={pal.id} className={slot === "available" && available.includes(pal.id) ? "selected" : ""} aria-pressed={slot === "available" ? available.includes(pal.id) : undefined} onClick={() => choose(pal)}><PalMark pal={pal} small /><span><b>{pal.name}</b><small>No. {pal.number}</small></span></button>)}</div>{visibleSearch.length < search.length && <button type="button" className="pal-picker-load-more" disabled={pickerLoading} aria-busy={pickerLoading} onClick={loadMorePicker}>{pickerLoading ? "Loading…" : "Load more"}</button>}</section></div>}
  </section>;
}

function Available({ pals, available, setAvailable, openPicker, compact = false, manualRoute = false }: { pals: PalData[]; available: string[]; setAvailable: (ids: string[]) => void; openPicker?: (slot: "available", trigger: HTMLElement) => void; compact?: boolean; manualRoute?: boolean }) {
  if (manualRoute) return <section className="home-breeding-slot home-available-control compact manual-owned-control"><div className="manual-owned-main" role="button" tabIndex={0} aria-label={available.length ? "Edit owned Pals" : "Select owned Pals"} onClick={(event) => openPicker?.("available", event.currentTarget)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openPicker?.("available", event.currentTarget); } }}><span className="slot-label">Pals You Own</span><strong>{available.length ? `${available.length} Pals selected` : "Select the Pals you already own"}</strong>{available.length ? <span className="manual-owned-preview">{available.slice(0, 4).map((id) => { const pal = pals.find((item) => item.id === id); return pal ? <PalMark key={id} pal={pal} small /> : null; })}{available.length > 4 && <b>+{available.length - 4}</b>}</span> : <small>Select Owned Pals</small>}</div><div className="manual-owned-actions">{available.length > 0 && <button type="button" onClick={() => openPicker?.("available", document.querySelector(".manual-owned-main") as HTMLElement)}>Edit</button>}{available.length > 0 && <button type="button" onClick={() => setAvailable([])}>Clear</button>}</div></section>;
  return <section className={`home-breeding-slot home-available-control${compact ? " compact" : ""}`} role="button" tabIndex={0} aria-label={available.length ? "Edit available Pals" : "Choose available Pals"} onClick={(event) => openPicker?.("available", event.currentTarget)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); openPicker?.("available", event.currentTarget); } }}><span className="slot-label">Available Pals</span><PalMark /><strong>{available.length ? `${available.length} selected` : "Choose available Pals"}</strong><small>{available.length ? "Your saved breeding roster" : "Add the Pals you can breed with"}</small><i>{available.length ? "Change Pals" : "Choose Pal"}</i></section>;
}

function Routes({ routes, copy }: { routes: ReturnType<typeof findRoutes>; copy: (value: string) => void }) {
  if (!routes.length) return <p className="breed-empty">No route found within this generation limit. Adjust the available Pals or maximum generations.</p>;
  return <div className="route-list">{routes.map((route, i) => <article key={i}><header><strong>{route.generations} generations</strong><button onClick={() => copy(route.steps.map((s, n) => `Step ${n + 1}: ${s.first.name} + ${s.second.name} → ${s.child.name}`).join("\n"))}>Copy Route</button><button onClick={() => copy(location.href)}>Copy Link</button></header>{route.generations === 0 ? <p>Target already available · 0 generations</p> : route.steps.map((step, n) => <div key={n}><b>Step {n + 1}</b><Result result={step} /></div>)}</article>)}</div>;
}
